[theme]
primaryColor = "#e83e8c"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "sans-serif"

[server]
# Enable more verbose error messages
enableCORS = false
enableXsrfProtection = false 